# Docker Compose файл для локальной среды React приложения

version: '3.8'

services:
  react-app-local:
    build:
      context: ..
      dockerfile: docker/Dockerfile.local
    ports:
      - "3000:3000"
    volumes:
      - ../app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development